apiVersion: v1
kind: ConfigMap
metadata:
  name: gemma-2b-it-epp
  namespace: default
data:
  default-plugins.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    featureGates:
    - dataLayer
    plugins:
    - type: queue-scorer
    - type: kv-cache-utilization-scorer
    - type: prefix-cache-scorer
    - type: metrics-data-source
      name: ray-source
      parameters:
        scheme: "http"
        path: "/"
    - type: model-server-protocol-metrics
      name: ray-extractor
      parameters:
        defaultEngine: "vllm"
        engineConfigs:
        - name: "vllm"
          kvUsageSpec: "ray_vllm_kv_cache_usage_perc"
          runningRequestsSpec: "ray_vllm_num_requests_running"
          queuedRequestsSpec: "ray_vllm_num_requests_waiting"
          cacheInfoSpec: "ray_vllm_cache_config_info"
    data:
      sources:
      - pluginRef: ray-source
        extractors:
        - pluginRef: ray-extractor

    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: queue-scorer
      - pluginRef: kv-cache-utilization-scorer
      - pluginRef: prefix-cache-scorer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gemma-2b-it-epp
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gemma-2b-it-epp
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferenceobjectives"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["inference.networking.k8s.io"]
  resources: ["inferencepools"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gemma-2b-it-epp
  namespace: default
subjects:
- kind: ServiceAccount
  name: gemma-2b-it-epp
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gemma-2b-it-epp
---
apiVersion: v1
kind: Service
metadata:
  name: gemma-2b-it-epp
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc-ext-proc
    port: 9002
    protocol: TCP
    targetPort: 9002
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    inferencepool: gemma-2b-it-epp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemma-2b-it-epp
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      inferencepool: gemma-2b-it-epp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        inferencepool: gemma-2b-it-epp
    spec:
      serviceAccountName: gemma-2b-it-epp
      containers:
      - args:
        - --pool-name
        - gemma-2b-it
        - --pool-namespace
        - default
        - --pool-group
        - inference.networking.k8s.io
        - --zap-encoder
        - json
        - --config-file
        - /config/default-plugins.yaml
        - --model-server-metrics-port
        - "8080"  # Ray Serve metrics port.
        - --v
        - "1"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: registry.k8s.io/gateway-api-inference-extension/epp:v1.4.0-rc.3
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: epp
        ports:
        - containerPort: 9002
          name: grpc
          protocol: TCP
        - containerPort: 9003
          name: grpc-health
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 9003
            service: inference-extension
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: plugins-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 130
      volumes:
      - configMap:
          defaultMode: 420
          name: gemma-2b-it-epp
        name: plugins-config-volume
