apiVersion: v1
kind: ConfigMap
metadata:
  name: gemma-2b-it-epp
  namespace: default
data:
  default-plugins.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    featureGates:
    - dataLayer
    plugins:
    - type: queue-scorer
    - type: kv-cache-utilization-scorer
    - type: prefix-cache-scorer
    - type: metrics-data-source
      name: ray-source
      parameters:
        scheme: "http"
        path: "/"
    - type: core-metrics-extractor
      name: ray-extractor
      parameters:
        defaultEngine: "vllm"
        engineConfigs:
        - name: "vllm"
          kvUsageSpec: "ray_vllm_kv_cache_usage_perc"
          runningRequestsSpec: "ray_vllm_num_requests_running"
          queuedRequestsSpec: "ray_vllm_num_requests_waiting"
          cacheInfoSpec: "ray_vllm_cache_config_info"
    data:
      sources:
      - pluginRef: ray-source
        extractors:
        - pluginRef: ray-extractor

    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: queue-scorer
      - pluginRef: kv-cache-utilization-scorer
      - pluginRef: prefix-cache-scorer
